# Generated by Django 6.0.4 on 2026-05-21 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Concert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('band_name', models.CharField(max_length=255)),
                ('description', models.TextField(help_text='Descrição da banda')),
                ('info_link', models.URLField(blank=True, null=True)),
                ('social_link', models.URLField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='concerts/')),
                ('start_datetime', models.DateTimeField()),
                ('location', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Exhibition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('area', models.CharField(choices=[('DESIGN', 'Design'), ('FOTO', 'Fotografia'), ('GAMES', 'Videojogos'), ('LABIA', 'Espaço Lábia')], default='DESIGN', max_length=10)),
                ('synopsis', models.TextField(help_text='Sinopse da exposição')),
                ('artists', models.TextField(help_text='Identificação dos artistas')),
                ('image', models.ImageField(upload_to='exhibitions/')),
                ('opening_hours', models.CharField(help_text='Ex: 09:00 - 18:00 (Flexível IPDJ)', max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('location', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Palestra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('speaker_name', models.CharField(max_length=255)),
                ('speaker_activity', models.CharField(help_text='Atividade/Cargo', max_length=255)),
                ('speaker_info_link', models.URLField(blank=True, help_text='Link para + info', null=True)),
                ('social_link', models.URLField(blank=True, help_text='Rede social ou Site', null=True)),
                ('registration_link', models.URLField(blank=True, help_text='Link para inscrição', null=True)),
                ('image', models.ImageField(upload_to='palestras/')),
                ('start_datetime', models.DateTimeField()),
                ('location', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SpecialZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('featured_projects', models.TextField()),
                ('image', models.ImageField(upload_to='special_zones/')),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('location', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SpeedHunting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('company_logo', models.ImageField(upload_to='speed_hunting/logos/')),
                ('start_datetime', models.DateTimeField()),
                ('location', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='VideoScreening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('director_team', models.CharField(help_text='Realizador/Equipa', max_length=255)),
                ('synopsis', models.TextField()),
                ('duration', models.CharField(max_length=100)),
                ('social_link', models.URLField(blank=True, help_text='Rede social do realizador/projeto', null=True)),
                ('image', models.ImageField(upload_to='video_screenings/')),
                ('start_datetime', models.DateTimeField()),
                ('location', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('mentor_name', models.CharField(max_length=255)),
                ('mentor_social', models.URLField(blank=True, null=True)),
                ('duration', models.CharField(help_text='Ex: 2 horas', max_length=100)),
                ('max_participants', models.IntegerField()),
                ('registration_link', models.URLField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='workshops/')),
                ('start_datetime', models.DateTimeField()),
                ('location', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
