# Generated by Django 6.0.4 on 2026-05-12 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('url', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('views', models.IntegerField(default=0)),
                ('is_hidden', models.BooleanField(default=False)),
            ],
        ),
    ]
