# Generated by Django 6.0.4 on 2026-05-21 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_page_button_link_page_button_text_page_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='button_link',
            new_name='cta_button_link',
        ),
        migrations.RenameField(
            model_name='page',
            old_name='button_text',
            new_name='cta_button_text',
        ),
        migrations.RenameField(
            model_name='page',
            old_name='date',
            new_name='event_date',
        ),
        migrations.RenameField(
            model_name='page',
            old_name='description',
            new_name='main_description',
        ),
        migrations.RenameField(
            model_name='page',
            old_name='title',
            new_name='main_title',
        ),
        migrations.RemoveField(
            model_name='page',
            name='is_hidden',
        ),
        migrations.AddField(
            model_name='page',
            name='is_live',
            field=models.BooleanField(default=True),
        ),
    ]
