# Generated by Django 6.0.4 on 2026-05-22 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_rename_button_link_page_cta_button_link_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='cta_button_link',
            new_name='button_link',
        ),
        migrations.RenameField(
            model_name='page',
            old_name='cta_button_text',
            new_name='button_text',
        ),
        migrations.RenameField(
            model_name='page',
            old_name='event_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='page',
            old_name='main_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='page',
            old_name='main_title',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='page',
            name='is_live',
        ),
        migrations.AddField(
            model_name='page',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
    ]
