# Generated by Django 6.0.4 on 2026-05-23 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_rename_page_fields'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='main_title',
            new_name='main_green_title',
        ),
        migrations.AddField(
            model_name='page',
            name='main_white_title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
