# Generated by Django 6.0.4 on 2026-05-23 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_rename_main_title_page_main_green_title_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='event_date',
            new_name='end_event_date',
        ),
        migrations.AddField(
            model_name='page',
            name='start_event_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
