# Generated by Django 6.0.4 on 2026-05-24 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_rename_event_date_page_end_event_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Concertos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('band_name', models.CharField(max_length=255)),
                ('description', models.TextField(help_text='Descrição da banda')),
                ('info_link', models.URLField(blank=True, null=True)),
                ('social_link', models.URLField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='concertos/')),
                ('start_datetime', models.DateTimeField()),
                ('location', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Exposicoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('area', models.CharField(choices=[('DESIGN', 'Design'), ('FOTO', 'Fotografia'), ('GAMES', 'Videojogos'), ('LABIA', 'Espaço Lábia')], default='DESIGN', max_length=10)),
                ('synopsis', models.TextField(help_text='Sinopse da exposição')),
                ('artists', models.TextField(help_text='Identificação dos artistas')),
                ('image', models.ImageField(upload_to='exposicoes/')),
                ('opening_hours', models.CharField(help_text='Ex: 09:00 - 18:00 (Flexível IPDJ)', max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('location', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Projecoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('director_team', models.CharField(help_text='Realizador/Equipa', max_length=255)),
                ('synopsis', models.TextField()),
                ('duration', models.CharField(max_length=100)),
                ('social_link', models.URLField(blank=True, help_text='Rede social do realizador/projeto', null=True)),
                ('image', models.ImageField(upload_to='projecoes/')),
                ('start_datetime', models.DateTimeField()),
                ('location', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SemanaLabia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('featured_projects', models.TextField()),
                ('image', models.ImageField(upload_to='semana_labia/')),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('location', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='Palestra',
            new_name='Palestras',
        ),
        migrations.RenameModel(
            old_name='Workshop',
            new_name='Workshops',
        ),
        migrations.DeleteModel(
            name='Concert',
        ),
        migrations.DeleteModel(
            name='Exhibition',
        ),
        migrations.DeleteModel(
            name='SpecialZone',
        ),
        migrations.DeleteModel(
            name='VideoScreening',
        ),
    ]
