# Generated by Django 6.0.4 on 2026-05-24 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_concertos_exposicoes_projecoes_semanalabia_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='url',
        ),
    ]
