# Generated by Django 6.0.4 on 2026-05-26 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_make_image_fields_optional'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cinema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('director_team', models.CharField(help_text='Realizador/Equipa', max_length=255)),
                ('synopsis', models.TextField()),
                ('duration', models.CharField(max_length=100)),
                ('social_link', models.URLField(blank=True, help_text='Rede social do realizador/projeto', null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='cinema/')),
                ('start_datetime', models.DateTimeField()),
                ('location', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SunsetTalks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('speaker_name', models.CharField(max_length=255)),
                ('speaker_activity', models.CharField(help_text='Atividade/Cargo', max_length=255)),
                ('speaker_info_link', models.URLField(blank=True, help_text='Link para + info', null=True)),
                ('social_link', models.URLField(blank=True, help_text='Rede social ou Site', null=True)),
                ('registration_link', models.URLField(blank=True, help_text='Link para inscrição', null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='sunset_talks/')),
                ('start_datetime', models.DateTimeField()),
                ('location', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Palestras',
        ),
        migrations.DeleteModel(
            name='Projecoes',
        ),
    ]
