# Generated by Django 6.0.4 on 2026-05-28 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_cinema_sunsettalks_delete_palestras_delete_projecoes'),
    ]

    operations = [
        migrations.AddField(
            model_name='speedhunting',
            name='category',
            field=models.CharField(blank=True, choices=[('DESIGN', 'Design'), ('FOTO', 'Fotografia'), ('MARKETING', 'Marketing'), ('PW', 'Programação'), ('SOM', 'Som'), ('VIDEO', 'Vídeo'), ('JOGOS', 'Videojogos'), ('OUTROS', 'Outros')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='speedhunting',
            name='company_description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
