# Generated by Django 6.0.4 on 2026-05-28 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_speedhunting_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshops',
            name='category',
            field=models.CharField(blank=True, choices=[('DESIGN', 'Design'), ('FOTO', 'Fotografia'), ('MARKETING', 'Marketing'), ('PW', 'Programação'), ('SOM', 'Som'), ('VIDEO', 'Vídeo'), ('JOGOS', 'Videojogos'), ('CINEMA', 'Cinema / TV'), ('OUTROS', 'Outros')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='speedhunting',
            name='category',
            field=models.CharField(blank=True, choices=[('DESIGN', 'Design'), ('FOTO', 'Fotografia'), ('MARKETING', 'Marketing'), ('PW', 'Programação'), ('SOM', 'Som'), ('VIDEO', 'Vídeo'), ('JOGOS', 'Videojogos'), ('CINEMA', 'Cinema / TV'), ('OUTROS', 'Outros')], max_length=50, null=True),
        ),
    ]
