# Generated by Django 6.0.4 on 2026-05-28 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_workshops_category_alter_speedhunting_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workshops',
            name='image',
        ),
    ]
