# Generated by Django 6.0.4 on 2026-05-28 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_remove_workshops_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='sunsettalks',
            name='category',
            field=models.CharField(blank=True, choices=[('DESIGN', 'Design'), ('FOTO', 'Fotografia'), ('MARKETING', 'Marketing'), ('PW', 'Programação'), ('SOM', 'Som'), ('VIDEO', 'Vídeo'), ('JOGOS', 'Videojogos'), ('CINEMA', 'Cinema / TV'), ('OUTROS', 'Outros')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sunsettalks',
            name='category_other',
            field=models.CharField(blank=True, help_text="Preencher quando categoria for 'Outros'", max_length=100, null=True),
        ),
    ]
