# Generated by Django 6.0.4 on 2026-05-29 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0017_exposicoes_area_to_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cinema',
            name='director_team',
            field=models.CharField(blank=True, help_text='Realizador/Equipa', max_length=255),
        ),
        migrations.AlterField(
            model_name='cinema',
            name='duration',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='cinema',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='cinema',
            name='start_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cinema',
            name='synopsis',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='cinema',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='concertos',
            name='band_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='concertos',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='concertos',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='concertos',
            name='start_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='semanalabia',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='semanalabia',
            name='end_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='semanalabia',
            name='featured_projects',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='semanalabia',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='semanalabia',
            name='start_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='semanalabia',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='speedhunting',
            name='company_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='speedhunting',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='speedhunting',
            name='start_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sunsettalks',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='sunsettalks',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='sunsettalks',
            name='speaker_activity',
            field=models.CharField(blank=True, help_text='Atividade/Cargo', max_length=255),
        ),
        migrations.AlterField(
            model_name='sunsettalks',
            name='speaker_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='sunsettalks',
            name='start_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sunsettalks',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='workshops',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='workshops',
            name='duration',
            field=models.CharField(blank=True, help_text='Ex: 2 horas', max_length=100),
        ),
        migrations.AlterField(
            model_name='workshops',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='workshops',
            name='max_participants',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workshops',
            name='mentor_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='workshops',
            name='start_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workshops',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
