# Generated by Django 6.0.4 on 2026-05-31 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0019_add_area_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='cinema',
            name='is_highlight',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='concertos',
            name='is_highlight',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='exposicoes',
            name='is_highlight',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sunsettalks',
            name='is_highlight',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workshops',
            name='is_highlight',
            field=models.BooleanField(default=False),
        ),
    ]
