# Generated by Django 6.0.4 on 2026-06-03 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0020_cinema_is_highlight_concertos_is_highlight_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exposicoes',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exposicoes',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='exposicoes',
            name='opening_hours',
            field=models.CharField(blank=True, help_text='Ex: 09:00 - 18:00 (Flexível IPDJ)', max_length=255),
        ),
        migrations.AlterField(
            model_name='exposicoes',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
