# Generated by Django 6.0.4 on 2026-06-18 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0021_alter_exposicoes_end_date_alter_exposicoes_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='speedhunting',
            name='company_website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
