# Generated by Django 6.0.4 on 2026-06-18 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0022_speedhunting_company_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speedhunting',
            name='company_description',
            field=models.TextField(blank=True, max_length=1500, null=True),
        ),
    ]
