# Generated by Django 6.0.4 on 2026-06-18 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0023_alter_speedhunting_company_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='speedhunting',
            name='company_facebook',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='speedhunting',
            name='company_instagram',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='speedhunting',
            name='company_linkedin',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='speedhunting',
            name='end_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
