[pytest]
DJANGO_SETTINGS_MODULE = core.settings
python_files = tests.py test_*.py *_test.py
testpaths = core apps
log_cli = true
log_cli_level = INFO
log_file = /app/logs/pytest.log
log_file_level = INFO